apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: wordpress-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Wordpress is the Schema for the wordpresses API
      displayName: Wordpress
      kind: Wordpress
      name: wordpresses.app.jxlwqq.github.io
      version: v1alpha1
  description: wordpress-operator
  displayName: wordpress-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - wordpress-operator
  links:
  - name: Wordpress Operator
    url: https://wordpress-operator.domain
  maintainers:
  - email: jxlwqq@gmail.com
    name: jxlwqq
  maturity: alpha
  provider:
    name: jxlwqq
    url: github.com/jxlwqq
  version: 0.0.0
